# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb66b290e5c748ed1ce322369d1c9aec901fbc73e29418d47f90119766108c5222445b9ec753f54bd0af6beaeaf27b80f465646dadbf081a4c4176ed013dfb06

test:
  secret_key_base: 6dbcf09a17d1154a56fa86046b04ef10c7e1c4cc8bd02599f25364d961dbc0fb53225b1c6bc411f05f309de19339a36737683d4217aaf3e57d93020de57b28ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
